language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-user ./udagram-user
  - docker tag udagram-user YOUR_DOCKER_HUB/udagram-user:latest
  - docker build -t udagram-feed ./udagram-feed
  - docker tag udagram-feed YOUR_DOCKER_HUB/udagram-feed:latest
  # - docker build -t udagram-frontend ./udagram-frontend
  # - docker tag udagram-frontend YOUR_DOCKER_HUB/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push YOUR_DOCKER_HUB/simple-node
