apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram
  labels:
    app: udagram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        app: udagram
    spec:
      containers:
      - name: udagram-user
        image: gonzalogarridopf/udagram-user
        ports:
        - containerPort: 8080
      # - name: udagram-feed
      #   image: gonzalogarridopf/udagram-feed
      #   ports:
      #   - containerPort: 80
      # - name: udagram-frontend
      #   image: gonzalogarridopf/udagram-frontend
      #   ports:
      #   - containerPort: 80