apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed
  labels:
    app: udagram-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-feed
  template:
    metadata:
      labels:
        app: udagram-feed
    spec:
      containers:
      - name: udagram-feed
        image: gonzalogarridopf/udagram-feed
        env:
        - name: POSTGRES_USERNAME
          value: "udacity"
        - name: POSTGRES_PASSWORD
          value: "udacity21"
        - name: POSTGRES_HOST
          value: "udagram.cfpkxcjzcqtk.us-east-2.rds.amazonaws.com"
        - name: POSTGRES_DB
          value: "udagram"
        - name: AWS_BUCKET
          value: "udagram-548866588322-dev"
        - name: AWS_REGION
          value: "us-west-2"
        - name: AWS_PROFILE
          value: "default"
        - name: URL
          value: "http://a6a0c3171e9844678b15ce78fa172469-843829554.us-east-2.elb.amazonaws.com:4200"
        - name: PORT
          value: "8081"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m" 
        ports:
        - containerPort: 8081