apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-app
  labels:
    run: udagram-feed-app
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    run: udagram-feed-app